### ISSUE TITLE
安卓模拟器无法运行

### ISSUE THREAD

**Issue by kira2015** [LiteAVSDK/Live_Flutter#31]
Log:
`
W/SoLoader( 4432): load library txsoundtouch from system path
W/SoLoader( 4432): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtxsoundtouch.so" not found
W/SoLoader( 4432): load library txsoundtouch false
W/SoLoader( 4432): load library txffmpeg from system path
W/SoLoader( 4432): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtxffmpeg.so" not found
W/SoLoader( 4432): load library txffmpeg false
W/SoLoader( 4432): load library livesdk from system path
W/SoLoader( 4432): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "liblivesdk.so" not found
W/SoLoader( 4432): load library livesdk false
W/SoLoader( 4432): load library liteavsdk from system path
W/SoLoader( 4432): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libliteavsdk.so" not found
W/SoLoader( 4432): load library liteavsdk false
E/chtv.rmzskanka( 4432): No implementation found for void com.tencent.liteav.base.Log.nativeWriteLogToNative(int, java.lang.String, java.lang.String) (tried Java_com_tencent_liteav_base_Log_nativeWriteLogToNative and Java_com_tencent_liteav_base_Log_nativeWriteLogToNative__ILjava_lang_String_2Ljava_lang_String_2)
E/AndroidRuntime( 4432): FATAL EXCEPTION: main
E/AndroidRuntime( 4432): Process: com.touchtv.rmzskankan, PID: 4432
E/AndroidRuntime( 4432): java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.base.Log.nativeWriteLogToNative(int, java.lang.String, java.lang.String) (tried Java_com_tencent_liteav_base_Log_nativeWriteLogToNative and Java_com_tencent_liteav_base_Log_nativeWriteLogToNative__ILjava_lang_String_2Ljava_lang_String_2)
E/AndroidRuntime( 4432): 	at com.tencent.liteav.base.Log.nativeWriteLogToNative(Native Method)
E/AndroidRuntime( 4432): 	at com.tencent.liteav.base.Log.i(SourceFile:177)
E/AndroidRuntime( 4432): 	at com.tencent.liteav.basic.log.TXCLog.i(SourceFile:36)
E/AndroidRuntime( 4432): 	at com.tencent.live.utils.Logger.info(Logger.java:12)
E/AndroidRuntime( 4432): 	at com.tencent.live.plugin.V2TXLivePremierPlugin.onMethodCall(V2TXLivePremierPlugin.java:45)
E/AndroidRuntime( 4432): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 4432): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 4432): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 4432): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 4432): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 4432): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4432): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 4432): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 4432): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4432): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 4432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 4432): Sending signal. PID: 4432 SIG: 9
Lost connection to device.`

**Comment by githubliuqi** [comment]
请在真机运行。
