### ISSUE TITLE
调动 V2TXLivePlayer 的 destroy() 方法会导致 app闪退

### ISSUE THREAD

**Issue by weishirongzhen** [LiteAVSDK/Live_Flutter#8]
E/AndroidRuntime( 8987): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 8987): 	at com.tencent.live.plugin.V2TXLivePlayerPlugin$V2TXLivePlayerObserverImpl.invokeListener(V2TXLivePlayerPlugin.java:520)
E/AndroidRuntime( 8987): 	at com.tencent.live.plugin.V2TXLivePlayerPlugin$V2TXLivePlayerObserverImpl.onStatisticsUpdate(V2TXLivePlayerPlugin.java:466)
E/AndroidRuntime( 8987): 	at com.tencent.live2.leb.b$17.run(TXLEBPlayerImpl.java:536)
E/AndroidRuntime( 8987): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime( 8987): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 8987): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime( 8987): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime( 8987): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8987): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime( 8987): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by EricPHPH** [comment]
遇到了相同的问题，不过不是每次都发生，只是偶尔出现。应该是原生那边destroy后将channel置为null了，onStatisticsUpdate方法这个时候异步调用了。导致空指针异常。建议在invokeListener中添加对mChannel的空判断。

**Comment by githubliuqi** [comment]
后续会修复完善。
